{% set name = "prance" %}
{% set version = "0.21.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prance-{{ version }}.tar.gz
  sha256: ce06feef8814c3436645f3b094e91067b1a111bc860a51f239f93437a8d4b00e

build:
  entry_points:
    - prance=prance.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - chardet >=3.0,<4
    - python >=3.6
    - pyyaml >=5.3,<6
    - requests >=2.22,<3
    - semver >=2.9,<3
    - six >=1.14,<2
    - click

test:
  imports:
    - prance
  commands:
    - pip check
    - prance --help
  requires:
    - pip
    # optional dependency needed only for `prance --help`
    - flex-swagger

about:
  home: https://github.com/jfinkhaeuser/prance
  summary: Resolving Swagger/OpenAPI 2.0 and 3.0.0 Parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
